title: 一个喜欢技术的图书馆员
email: hfl@huangfeilong.com
description: 我不排斥理论，但是我更推崇技术，没有技术实现，理论只是空谈。
baseurl: ""
url: ""
twitter_username: hfl
github_username:  hfl

# Build settings
markdown: kramdown
theme: minima
minima:
  date_format: "%Y年%m月%d日"
plugins:
  - jekyll-feed
jekyll_compose:
    auto_open: true
