title: 飝龘圕
email: huang_fl at sina.com
description: 龙行龘龘，前程朤朤。
baseurl: ""
url: ""
timezone: Asia/Chongqing
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 15
paginate_path: "/blog/page:num/"
minima:
  date_format: "%Y年%-m月%-d日"
